# vim: set ft=conf:

hello

## Core Scripting
coreutils-prefixed
curl
dig
fd
findutils
git
gnugrep
gnused
jq
man
openssh
rclone
ripgrep
rsync
stow
zstd

## Workstation
bat
delta
eza
fish
fzf
gron
hexyl
hyperfine
ncdu
neovim-unwrapped
pueue
rink
screen
tealdeer
unison
unison-fsmonitor

## Development
cargo-about
cargo-binstall
cargo-flamegraph
cargo-nextest
cargo-show-asm
ccache
git-branchless
git-lfs
lua-language-server
ninja
nixd
nixfmt
rr
ruff
rustup
samply
shellcheck
stylua
universal-ctags
