" Color Scheme
colorscheme solarized8

" set guifont=Monaco:h14
" set guifont=Source\ Code\ Pro:h15
" set guifont=Anonymice\ Nerd\ Font\ Complete\ Mono:h16
" set guifont=DejaVu\ Sans\ Mono:h18
" set guifont=Menlo:h15
if g:not_nvim
	set guifont=Comic\ Code\ Regular:h18
endif
set lines=32 columns=90
